# Generated by Django 4.2 on 2023-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='firstname',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='lastname',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
