# Generated by Django 4.2 on 2023-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
