# Generated by Django 4.2 on 2023-07-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extendeduser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='extendeduser',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
