# Generated by Django 4.2 on 2023-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_firstname_extendeduser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='sub',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
