# Generated by Django 4.2 on 2023-06-07 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='amount',
            field=models.IntegerField(default=99, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
