# Generated by Django 4.2 on 2023-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_good_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
