# Generated by Django 4.2 on 2023-06-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good_manufacturer'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='goods.good'),
        ),
    ]
